[2023-03-14T22:46:18.292+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:46:18.298+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:46:18.299+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:46:18.299+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-03-14T22:46:18.300+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:46:18.308+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): JsonToCSV> on 2023-03-14 22:41:08.560415+00:00
[2023-03-14T22:46:18.313+0000] {standard_task_runner.py:55} INFO - Started process 571 to run task
[2023-03-14T22:46:18.317+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'JsonToCSV', 'manual__2023-03-14T22:41:08.560415+00:00', '--job-id', '638', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp97jnad85']
[2023-03-14T22:46:18.318+0000] {standard_task_runner.py:83} INFO - Job 638: Subtask JsonToCSV
[2023-03-14T22:46:18.371+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [running]> on host 9cebcb3c5b96
[2023-03-14T22:46:18.612+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=JsonToCSV
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T22:41:08.560415+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T22:41:08.560415+00:00
[2023-03-14T22:46:18.621+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-03-14T22:46:18.622+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-03-14T22:46:18.875+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 28, in json_to_csv
    hook.invoke_lambda(function_name="json_to_csv",payload=pay_load)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 74, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 924, in _make_api_call
    headers=additional_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 991, in _convert_to_request_dict
    api_params, operation_model
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Payload, value: {'s3_bucket': 'spotify-top-50', 's3_folder': '2023-03-14'}, type: <class 'dict'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object
[2023-03-14T22:46:18.882+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=JsonToCSV, execution_date=20230314T224108, start_date=20230314T224618, end_date=20230314T224618
[2023-03-14T22:46:18.889+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 638 for task JsonToCSV (Parameter validation failed:
Invalid type for parameter Payload, value: {'s3_bucket': 'spotify-top-50', 's3_folder': '2023-03-14'}, type: <class 'dict'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object; 571)
[2023-03-14T22:46:18.939+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T22:46:18.955+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
