[2023-03-11T23:25:23.732+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:22:05.182734+00:00 [queued]>
[2023-03-11T23:25:23.737+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:22:05.182734+00:00 [queued]>
[2023-03-11T23:25:23.738+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T23:25:23.738+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-03-11T23:25:23.739+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T23:25:23.746+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): GetSongsFromPlaylist> on 2023-03-11 23:22:05.182734+00:00
[2023-03-11T23:25:23.751+0000] {standard_task_runner.py:55} INFO - Started process 781 to run task
[2023-03-11T23:25:23.755+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'GetSongsFromPlaylist', 'manual__2023-03-11T23:22:05.182734+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp47y8ux0i']
[2023-03-11T23:25:23.756+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask GetSongsFromPlaylist
[2023-03-11T23:25:23.804+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:22:05.182734+00:00 [running]> on host 4fa3b0adb91e
[2023-03-11T23:25:23.846+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=GetSongsFromPlaylist
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T23:22:05.182734+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-11T23:22:05.182734+00:00
[2023-03-11T23:25:24.327+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-03-11T23:25:24.328+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/extract.py", line 79, in get_songs_from_playlist
    ti.xcom_push(key='songs_df', value=songs_df)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-11T23:25:24.339+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=GetSongsFromPlaylist, execution_date=20230311T232205, start_date=20230311T232523, end_date=20230311T232524
[2023-03-11T23:25:24.351+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task GetSongsFromPlaylist (Object of type DataFrame is not JSON serializable; 781)
[2023-03-11T23:25:24.383+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-11T23:25:24.396+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
