[2023-03-21T22:48:31.237+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spotify_Data_ETL.StoreSongArtistBridge manual__2023-03-21T22:47:20.265233+00:00 [queued]>
[2023-03-21T22:48:31.242+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spotify_Data_ETL.StoreSongArtistBridge manual__2023-03-21T22:47:20.265233+00:00 [queued]>
[2023-03-21T22:48:31.243+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T22:48:31.243+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 3
[2023-03-21T22:48:31.243+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T22:48:31.250+0000] {taskinstance.py:1303} INFO - Executing <Task(S3ToSnowflakeOperator): StoreSongArtistBridge> on 2023-03-21 22:47:20.265233+00:00
[2023-03-21T22:48:31.255+0000] {standard_task_runner.py:55} INFO - Started process 21878 to run task
[2023-03-21T22:48:31.258+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'StoreSongArtistBridge', 'manual__2023-03-21T22:47:20.265233+00:00', '--job-id', '2265', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp6pogpdmz']
[2023-03-21T22:48:31.259+0000] {standard_task_runner.py:83} INFO - Job 2265: Subtask StoreSongArtistBridge
[2023-03-21T22:48:31.302+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.StoreSongArtistBridge manual__2023-03-21T22:47:20.265233+00:00 [running]> on host 1fd7b08731f2
[2023-03-21T22:48:31.341+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=StoreSongArtistBridge
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T22:47:20.265233+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T22:47:20.265233+00:00
[2023-03-21T22:48:31.342+0000] {s3_to_snowflake.py:146} INFO - Executing COPY command...
[2023-03-21T22:48:31.349+0000] {base.py:73} INFO - Using connection ID 'snowflake_connection' for task execution.
[2023-03-21T22:48:31.351+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.49-linuxkit-aarch64-with-debian-11.6
[2023-03-21T22:48:31.352+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-21T22:48:31.352+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-21T22:48:31.781+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=True]
[2023-03-21T22:48:31.859+0000] {cursor.py:751} INFO - query execution done
[2023-03-21T22:48:31.861+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-21T22:48:31.863+0000] {sql.py:375} INFO - Running statement: COPY INTO SpotifyTop50USA.song_artist
FROM @s3_snowflake_stage/
files=('2023-03-21/song_artist_bridge.csv')
file_format=DATA_CSV, parameters: None
[2023-03-21T22:48:31.864+0000] {cursor.py:738} INFO - query: [COPY INTO SpotifyTop50USA.song_artist FROM @s3_snowflake_stage/ files=('2023-03-...]
[2023-03-21T22:48:32.013+0000] {cursor.py:751} INFO - query execution done
[2023-03-21T22:48:32.030+0000] {connection.py:586} INFO - closed
[2023-03-21T22:48:32.063+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-21T22:48:32.201+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/transfers/s3_to_snowflake.py", line 147, in execute
    snowflake_hook.run(copy_query, self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 091016 (22000): 01ab1a78-0004-6150-0000-00552087e109: Remote file 's3://spotify-top-50/2023-03-21/song_artist_bridge.csv' was not found. If you are running a copy command, please make sure files are not deleted when they are being loaded or files are not being loaded into two different tables concurrently with auto purge option.
[2023-03-21T22:48:32.228+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=StoreSongArtistBridge, execution_date=20230321T224720, start_date=20230321T224831, end_date=20230321T224832
[2023-03-21T22:48:32.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2265 for task StoreSongArtistBridge (091016 (22000): 01ab1a78-0004-6150-0000-00552087e109: Remote file 's3://spotify-top-50/2023-03-21/song_artist_bridge.csv' was not found. If you are running a copy command, please make sure files are not deleted when they are being loaded or files are not being loaded into two different tables concurrently with auto purge option.; 21878)
[2023-03-21T22:48:32.316+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T22:48:32.333+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
