[2023-03-16T05:10:01.677+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateAndLoadSongFact.ValidateSongFact manual__2023-03-16T05:02:48.467376+00:00 [queued]>
[2023-03-16T05:10:01.683+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateAndLoadSongFact.ValidateSongFact manual__2023-03-16T05:02:48.467376+00:00 [queued]>
[2023-03-16T05:10:01.683+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T05:10:01.684+0000] {taskinstance.py:1280} INFO - Starting attempt 10 of 10
[2023-03-16T05:10:01.684+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T05:10:01.691+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ValidateAndLoadSongFact.ValidateSongFact> on 2023-03-16 05:02:48.467376+00:00
[2023-03-16T05:10:01.696+0000] {standard_task_runner.py:55} INFO - Started process 9154 to run task
[2023-03-16T05:10:01.700+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'ValidateAndLoadSongFact.ValidateSongFact', 'manual__2023-03-16T05:02:48.467376+00:00', '--job-id', '1216', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmptavv58qg']
[2023-03-16T05:10:01.700+0000] {standard_task_runner.py:83} INFO - Job 1216: Subtask ValidateAndLoadSongFact.ValidateSongFact
[2023-03-16T05:10:01.746+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.ValidateAndLoadSongFact.ValidateSongFact manual__2023-03-16T05:02:48.467376+00:00 [running]> on host 18c42e4ef76b
[2023-03-16T05:10:01.933+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=ValidateAndLoadSongFact.ValidateSongFact
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T05:02:48.467376+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T05:02:48.467376+00:00
[2023-03-16T05:10:01.934+0000] {logging_mixin.py:137} INFO - {"track_id":{"0":"1bDbXMyjaUIooNwFE9wn0N","2":"1xK59OXxi2TAAAbmZK0kBL","3":"0VjIjW4GlUZAMYd2vXMi3b","4":"5IgjP7X4th6nMNDh4akUHb","5":"1DxEbt6OSbrkRthk6pjZue","8":"3r8RuvgbX9s7ammBn07D3W","9":"4FyesJzVpA39hbYvcseO2d","10":"561jH07mF1jHuk7KlaeF0s","11":"0CYTGMBYkwUxrj1MWDLrC5","12":"6otePxalBK8AVa20xhZYVQ","13":"54ipXppHLA8U4yqpOFTUhr","14":"4iZ4pt7kvcaH6Yo8UoZ4s2","15":"0JXXNGljqupsJaZsgSbMZV","16":"4NoOME4Dhf4xgxbHDT7VGe","18":"2mnXxnrX5vCGolNkaFvVeM","20":"4fYte8ZvTK14NEhAOZocBi","21":"1lRtH4FszTrwwlK5gTSbXO","24":"2CeKVsFFXG4QzA415QygGb","25":"2mpoNBkngUEwnaKoBhZ0vl","27":"2tTmW7RDtMQtBk7m2rYeSw","29":"2L9N0zZnd37dwF0clgxMGI","30":"6UN73IYd0hZxLi8wFPMQij","31":"5XeFesFbtLpXzIVDNQP22n","32":"5odlY52u43F5BjByhxg7wg","33":"7jtQIBanIiJOMS6RyCx6jZ","34":"04CqLjewJiSAqM210vZAmT","35":"7MXVkk9YMctZqd1Srtv4MB","37":"65FftemJ1DbbZ45DUfHJXE","38":"38UYeBLfvpnDSG9GznZdnL","40":"55ZATsjPlTeSTNJOuW90pW","42":"5mHdCZtVyb4DcJw8799hZp","44":"1zsPaEkglFvxjAhrM8yhpr","46":"1Y3LN4zO1Edc2EluIoSPJN","48":"0V3wPSX9ygBnCm8psDIegu","49":"78Sw5GDo6AlGwTwanjXbGh","50":"7K3BhSpAxZBznislvUMVtn","51":"2LBqCSwhJGcFQeTHMVGwy3","52":"4uUG5RXrOk84mYEfFvj3cK","54":"5ww2BF9slyYgNOk37BlC4u","55":"0NZPBYD5qbEWRs3PrGiRkT","57":"0WtM2NBVQNNJLh6scP13H8","59":"4FAKtPVycI4DxoOHC01YqD","61":"2dHHgzDwk4BJdRwy9uXhTO","64":"4Dvkj6JhhA12EX05fT7y2e","65":"4nrPB8O7Y7wsOCJdgXkthe","67":"6AQbmUe0Qwf5PZnt4HmTXv","69":"1Qrg8KqiBpW07V7PNxwwwL","70":"4W4fNrZYkobj539TOWsLO2","72":"0DWdj2oZMBFSzRsi2Cvfzf","74":"4DHcnVTT87F0zZhRPYmZ3B"},"popularity":{"0":90,"2":89,"3":89,"4":89,"5":88,"8":89,"9":89,"10":89,"11":88,"12":84,"13":84,"14":89,"15":90,"16":82,"18":85,"20":47,"21":90,"24":86,"25":89,"27":91,"29":87,"30":90,"31":90,"32":88,"33":60,"34":80,"35":90,"37":91,"38":87,"40":84,"42":79,"44":89,"46":90,"48":92,"49":92,"50":81,"51":88,"52":93,"54":93,"55":84,"57":93,"59":86,"61":94,"64":89,"65":96,"67":95,"69":93,"70":0,"72":94,"74":75},"date":{"0":"2023-03-16","2":"2023-03-16","3":"2023-03-16","4":"2023-03-16","5":"2023-03-16","8":"2023-03-16","9":"2023-03-16","10":"2023-03-16","11":"2023-03-16","12":"2023-03-16","13":"2023-03-16","14":"2023-03-16","15":"2023-03-16","16":"2023-03-16","18":"2023-03-16","20":"2023-03-16","21":"2023-03-16","24":"2023-03-16","25":"2023-03-16","27":"2023-03-16","29":"2023-03-16","30":"2023-03-16","31":"2023-03-16","32":"2023-03-16","33":"2023-03-16","34":"2023-03-16","35":"2023-03-16","37":"2023-03-16","38":"2023-03-16","40":"2023-03-16","42":"2023-03-16","44":"2023-03-16","46":"2023-03-16","48":"2023-03-16","49":"2023-03-16","50":"2023-03-16","51":"2023-03-16","52":"2023-03-16","54":"2023-03-16","55":"2023-03-16","57":"2023-03-16","59":"2023-03-16","61":"2023-03-16","64":"2023-03-16","65":"2023-03-16","67":"2023-03-16","69":"2023-03-16","70":"2023-03-16","72":"2023-03-16","74":"2023-03-16"}}
[2023-03-16T05:10:01.935+0000] {logging_mixin.py:137} INFO - ['artist_id', 'artist_name', 'followers', 'popularity']
[2023-03-16T05:10:01.936+0000] {logging_mixin.py:137} INFO - song_fact
[2023-03-16T05:10:01.946+0000] {logging_mixin.py:137} INFO -                   track_id  popularity       date
0   1bDbXMyjaUIooNwFE9wn0N          90 2023-03-16
2   1xK59OXxi2TAAAbmZK0kBL          89 2023-03-16
3   0VjIjW4GlUZAMYd2vXMi3b          89 2023-03-16
4   5IgjP7X4th6nMNDh4akUHb          89 2023-03-16
5   1DxEbt6OSbrkRthk6pjZue          88 2023-03-16
8   3r8RuvgbX9s7ammBn07D3W          89 2023-03-16
9   4FyesJzVpA39hbYvcseO2d          89 2023-03-16
10  561jH07mF1jHuk7KlaeF0s          89 2023-03-16
11  0CYTGMBYkwUxrj1MWDLrC5          88 2023-03-16
12  6otePxalBK8AVa20xhZYVQ          84 2023-03-16
13  54ipXppHLA8U4yqpOFTUhr          84 2023-03-16
14  4iZ4pt7kvcaH6Yo8UoZ4s2          89 2023-03-16
15  0JXXNGljqupsJaZsgSbMZV          90 2023-03-16
16  4NoOME4Dhf4xgxbHDT7VGe          82 2023-03-16
18  2mnXxnrX5vCGolNkaFvVeM          85 2023-03-16
20  4fYte8ZvTK14NEhAOZocBi          47 2023-03-16
21  1lRtH4FszTrwwlK5gTSbXO          90 2023-03-16
24  2CeKVsFFXG4QzA415QygGb          86 2023-03-16
25  2mpoNBkngUEwnaKoBhZ0vl          89 2023-03-16
27  2tTmW7RDtMQtBk7m2rYeSw          91 2023-03-16
29  2L9N0zZnd37dwF0clgxMGI          87 2023-03-16
30  6UN73IYd0hZxLi8wFPMQij          90 2023-03-16
31  5XeFesFbtLpXzIVDNQP22n          90 2023-03-16
32  5odlY52u43F5BjByhxg7wg          88 2023-03-16
33  7jtQIBanIiJOMS6RyCx6jZ          60 2023-03-16
34  04CqLjewJiSAqM210vZAmT          80 2023-03-16
35  7MXVkk9YMctZqd1Srtv4MB          90 2023-03-16
37  65FftemJ1DbbZ45DUfHJXE          91 2023-03-16
38  38UYeBLfvpnDSG9GznZdnL          87 2023-03-16
40  55ZATsjPlTeSTNJOuW90pW          84 2023-03-16
42  5mHdCZtVyb4DcJw8799hZp          79 2023-03-16
44  1zsPaEkglFvxjAhrM8yhpr          89 2023-03-16
46  1Y3LN4zO1Edc2EluIoSPJN          90 2023-03-16
48  0V3wPSX9ygBnCm8psDIegu          92 2023-03-16
49  78Sw5GDo6AlGwTwanjXbGh          92 2023-03-16
50  7K3BhSpAxZBznislvUMVtn          81 2023-03-16
51  2LBqCSwhJGcFQeTHMVGwy3          88 2023-03-16
52  4uUG5RXrOk84mYEfFvj3cK          93 2023-03-16
54  5ww2BF9slyYgNOk37BlC4u          93 2023-03-16
55  0NZPBYD5qbEWRs3PrGiRkT          84 2023-03-16
57  0WtM2NBVQNNJLh6scP13H8          93 2023-03-16
59  4FAKtPVycI4DxoOHC01YqD          86 2023-03-16
61  2dHHgzDwk4BJdRwy9uXhTO          94 2023-03-16
64  4Dvkj6JhhA12EX05fT7y2e          89 2023-03-16
65  4nrPB8O7Y7wsOCJdgXkthe          96 2023-03-16
67  6AQbmUe0Qwf5PZnt4HmTXv          95 2023-03-16
69  1Qrg8KqiBpW07V7PNxwwwL          93 2023-03-16
70  4W4fNrZYkobj539TOWsLO2           0 2023-03-16
72  0DWdj2oZMBFSzRsi2Cvfzf          94 2023-03-16
74  4DHcnVTT87F0zZhRPYmZ3B          75 2023-03-16
[2023-03-16T05:10:01.948+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 81, in validate_data
    raise ValueError("{} doesn't contain the correct rows".format(table))
ValueError: song_fact doesn't contain the correct rows
[2023-03-16T05:10:01.955+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=ValidateAndLoadSongFact.ValidateSongFact, execution_date=20230316T050248, start_date=20230316T051001, end_date=20230316T051001
[2023-03-16T05:10:01.961+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1216 for task ValidateAndLoadSongFact.ValidateSongFact (song_fact doesn't contain the correct rows; 9154)
[2023-03-16T05:10:01.993+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-16T05:10:02.010+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
