[2023-03-15T19:19:10.732+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-15T19:19:10.736+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-15T19:19:10.737+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:19:10.737+0000] {taskinstance.py:1280} INFO - Starting attempt 8 of 8
[2023-03-15T19:19:10.737+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:19:10.744+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): TransformData> on 2023-03-14 22:41:08.560415+00:00
[2023-03-15T19:19:10.748+0000] {standard_task_runner.py:55} INFO - Started process 599 to run task
[2023-03-15T19:19:10.751+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'TransformData', 'manual__2023-03-14T22:41:08.560415+00:00', '--job-id', '681', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp3g315x0d']
[2023-03-15T19:19:10.752+0000] {standard_task_runner.py:83} INFO - Job 681: Subtask TransformData
[2023-03-15T19:19:10.795+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [running]> on host af46459234d2
[2023-03-15T19:19:10.959+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=TransformData
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T22:41:08.560415+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T22:41:08.560415+00:00
[2023-03-15T19:19:10.994+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

[2023-03-15T19:19:10.996+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 40, in transform_data
    artist_fact=artist_fact[['artist_id','artist_name','followers','popularity']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['popularity'] not in index"
[2023-03-15T19:19:11.004+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=TransformData, execution_date=20230314T224108, start_date=20230315T191910, end_date=20230315T191911
[2023-03-15T19:19:11.009+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 681 for task TransformData ("['popularity'] not in index"; 599)
[2023-03-15T19:19:11.043+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-15T19:19:11.061+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
